# Generated by Django 5.2.15 on 2026-06-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aluno_id_alter_curso_id_alter_departamento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='semestre_letivo_defesa',
            field=models.CharField(blank=True, choices=[('2020/1', '2020/1'), ('2020/2', '2020/2'), ('2021/1', '2021/1'), ('2021/2', '2021/2'), ('2022/1', '2022/1'), ('2022/2', '2022/2'), ('2023/1', '2023/1'), ('2023/2', '2023/2'), ('2024/1', '2024/1'), ('2024/2', '2024/2'), ('2025/1', '2025/1'), ('2025/2', '2025/2'), ('2026/1', '2026/1'), ('2026/2', '2026/2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadeacademica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
